# @package _global_
defaults:
  - JIT-Baseline
  - _self_

name: Contrastive-FM

algorithms:
  contrastive:
    _target_: prx.algorithm.contrastive_flow_matching.ContrastiveFlowMatching
    lambda_weight: 0.05
