# @package _global_
defaults:
  - JIT-Baseline
  - _self_

name: LPIPS
group: JIT-Benchmark
algorithms:
  lpips:
    _target_: prx.algorithm.lpips.LPIPS
    lpips_weight: 0.1
    lpips_net: vgg
    t_threshold: 1
    resize_factor: 0.5

save_folder: checkpoints/LPIPS