# @package _global_
defaults:
  - JIT-Baseline
  - _self_

name: Perceptual_DINO
group: JIT-Benchmark
algorithms:
  pdino:
    _target_: prx.algorithm.perceptual_dino.PerceptualDINO
    pdino_weight: 0.01
    encoder: dinov2_vitb14_reg  # or dinov3_vitl16
    t_threshold: 1
    resize_resolution: 224
trainer:
  save_folder: checkpoints/Perceptual_DINO