# @package dataset.eval_dataset
# UNSPLASH evaluation dataset
# Standard evaluation set for image quality assessment

_target_: dataset.StreamingProcessedDataset
local:
  - /mnt/data/datasets/gen_ai/t2i_1024_t5gemma2b/UNSPLASH

caption_keys:
  - [caption_llm_s, 1.]
  - [caption, 1.]
  - [caption_alt, 1.]
text_tower: t5gemma2b-256-bf16 
prompt_max_tokens: 256
cache_limit: 8tb
download_timeout: 7200
drop_last: true
shuffle: true
batching_method: device_per_stream
prefetch_factor: 2
num_workers: 8
persistent_workers: true
pin_memory: true
has_mask_text_latents: true
transforms:
  - _target_: dataset.transforms.ArAwareResize
    default_image_size: ${image_size}
    patch_size_pixels: ${patch_size_pixels}
transforms_targets:
  - image
