# @package _global_
defaults:
  - JIT-Baseline
  - _self_

name: SPRINT

algorithms:
  sprint:
    _target_: algorithm.sprint.SPRINT
    route_start: 2
    route_end: 12
    routing_probability: 0.75
    detach: false
    seed: 42
    train_only: false
