# @package _global_
defaults:
  - Flux-Baseline
  - _self_

name: REPA-Dinov3

algorithms:
  repa:
    _target_: prx.algorithm.repa.REPA
    lambda_weight: 0.5
    layer_index: 7
    encoder: "dinov3_vitl16"
    compile_encoder: true
